### ISSUE TITLE
Vet KPCC Plus in 3.4.1

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#104]
AC

1) Confirm the process for turning on / off the KPCC Plus Stream in app is still sane

**Comment by ewr** [comment]
There appears to be an issue where the KPCC Plus dropdown option goes away after doing something that isn't the live stream. A flag gets set when moving to a non-live-stream view, and isn't unset by selecting the live stream in the menu. 

It shouldn't be a difficult fix, but I do think it's probably worth addressing with a release. Updating the logic for knowing whether we're in a drive probably makes sense at the same time.
