### ISSUE TITLE
Missing Internet Connection Causes On-Demand Crash

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#107]
<img width="971" alt="screen shot 2015-10-30 at 8 47 26 am" src="https://cloud.githubusercontent.com/assets/204350/10846020/e01e935c-7ee2-11e5-8da7-8515fe14e751.png">

This appears to be an issue unregistering our player observers if the player never actually played, apparently because the Internet connection wasn't active. The issue exists in 3.4.0 - 3.4.2.

#### in NSKVODeallocate

* Number of crashes: 40
* Impacted devices: 40

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fa3268f5d3a7f76b14b996](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fa3268f5d3a7f76b14b996)

**Comment by chris-fuller** [comment]
Repro:

  1. Start playing on demand episode
  2. Turn on airplane mode
  3. Swipe to next episode
