### ISSUE TITLE
FBSDKAppEventsStateManager.m line 61

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#116]
#### in +[FBSDKAppEventsStateManager retrievePersistedAppEventsStates]

* Number of crashes: 5
* Impacted devices: 5

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fc062bf5d3a7f76b1f1f4a](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fc062bf5d3a7f76b1f1f4a)

**Comment by ewr** [comment]
Apparently a Facebook issue.
