### ISSUE TITLE
Badge number doesn't make sense for news alert

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#118]
The breaking news alert currently sets a badge number, which doesn't make sense in its current implementation. There's no list of alerts, and no ability for the alert to do anything other than start playing the live stream.

The icon badge logic should just be removed.

**Comment by chris-fuller** [comment]
Closing for now since it looks like it will be handled server-side.

Related SCPRv4 Issue: https://github.com/SCPR/SCPRv4/issues/402
