### ISSUE TITLE
Need to support DAAST Format for Ad Response

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#121]
Currently ads use an overloaded VAST for audio. We're working on switching our ad infrastructure over to DAAST, which is similar but designed for audio. 

* [ ] Preroll should parse and handle either VAST or DAAST responses, without knowing which one it will receive.
* [ ] Preroll should support multiple impression URLs, as allowed by the spec
* [ ] Preroll should correctly hit the companion ad's creativeView tracking URL when creative is displayed and the screen is unlocked (if possible... if not, just when we think we're displaying it).

**Comment by chris-fuller** [comment]
Related Issue: https://github.com/SCPR/KPCC-iPhone/issues/126

**Comment by chris-fuller** [comment]
If appropriate, also try to improve logic to avoid crashing when an unexpected response format is encountered.
