### ISSUE TITLE
Program assets need update flow that doesn't involve app release

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#122]
Currently, programs have two assets: a small image for the programs list and a background tile that is displayed when the show is on-air or being played on-demand. The former is shipped inside the application, and can only be updated via an app release. The latter is loaded via a web server, and is probably not cached.

We need a way to ship asset updates that are cached by the app client, without having to do an app release.

**Comment by vsinghkpcc** [comment]
Addressed in a recent release.
