### ISSUE TITLE
Project housekeeping and optimization

### ISSUE THREAD

**Issue by chris-fuller** [SCPR/KPCC-iPhone#125]
Some initial thoughts (based on the current time to compile which ideally could be improved):

  * Housekeeping
    * Fix all project warnings
    * Enable: Treat warnings as errors
  * Optimization
    * Migrate some pods to frameworks (t.b.d.)
    * Remove some dependencies (t.b.d.)

**Comment by chris-fuller** [comment]
Look into Swift compiler options - possibly optimization level.

**Comment by chris-fuller** [comment]
For some reason #163 is including commits that are already on develop, so attaching this screenshot which shows just the commits relevant to the cleanup.

<img width="998" alt="screen shot 2016-03-11 at 4 57 16 pm" src="https://cloud.githubusercontent.com/assets/16296673/13719469/00f4327c-e7ab-11e5-993c-d69d6f7ae9f0.png">

**Comment by chris-fuller** [comment]
On branch `125-project-housekeeping`:

* The following dependencies have been removed: JWTDecode, KSReachability, Lock, Lock-Facebook, Lock-Twitter, Mixpanel, Nielsen, SimpleKeychain and TMReachability
* All remaining dependencies have been updated to their latest versions, except for AFNetworking and Parse SDK.
* All compiler warnings have been fixed
* All static analyzer errors have been fixed, except for some coming from Parse SDK
* No pods have been migrated to frameworks (not necessary right now)
* The "treat warnings as errors" build setting has been enabled
* The Swift optimization level seems set to an appropriate setting currently

Recommendations:

* Upgrade AFNetworking and Parse SDK to their latest versions.

**Comment by chris-fuller** [comment]
Let's wait until a successful 3.4.3 release before merging `125-project-housekeeping` to `develop`.

**Comment by chris-fuller** [comment]
Looks like we'll have a bit more work to do on `125-project-housekeeping` before merging to `develop`:

* New Google SDK requires some additional configuration
* Parse SDK is crashing

**Comment by chris-fuller** [comment]
@sean @vijay: Unless anyone objects, I think we should move ahead with this now and I will finish this ticket along with #186. The thinking is we need to fix the Parse SDK crashing either way. Plus this branch has the old SSO work removed, which is ideal for starting the new SSO work, especially since we have a very specific use case now.

**Comment by chris-fuller** [comment]
@vsinghkpcc: Would you mind moving this to this sprint once you're able to get Sean in the loop?

**Comment by chris-fuller** [comment]
On branch `125-project-housekeeping`:

* Parse SDK has been updated to version 1.13
* Flurry SDK has been updated to version 7.6
* Facebook SDK has been updated to version 4.12
* New compiler warnings have been fixed

**Comment by chris-fuller** [comment]
On branch `125-project-housekeeping`:

* AFNetworking has been updated to version 3.1 (from 2.6.3)

**Comment by chris-fuller** [comment]
On branch `125-project-housekeeping`:

* AFNetworking has been updated to version 3.1 (from 2.6.3)

**Comment by chris-fuller** [comment]
On branch `125-project-housekeeping`:

* Set ITSAppUsesNonExemptEncryption to false

**Comment by chris-fuller** [comment]
Regarding setting `ITSAppUsesNonExemptEncryption` to `false`. This should be the setting we need. And can easily be removed or changed to `true` as necessary. When we go to do our `3.4.4` release, we should know if we are good with this setting or not.

**Comment by chris-fuller** [comment]
@sdillingham When you have a minute, would you mind please letting me and @vsinghkpcc know how you feel about moving forward with this branch (i.e. merging to `develop` and using this as the base for our SSO work)?

I've been running this branch in development and have not experienced any blatant issues, but since all dependencies have been touched (either removed or updated), we will need to do thorough testing before release. But since we will need to do that anyway due to the major SSO implementation, it could be a win-win. We just want some consensus that this is the right move before merging. Please give us the final sign-off before we do. Or we can chat more about this if you deem necessary. Thanks Sean!

**Comment by sdillingham** [comment]
I'm comfortable merging this into `develop`. I'm curious why the analytics event tracking on individual menu actions looks like it's been removed? for example:

https://github.com/SCPR/KPCC-iPhone/pull/163/files#diff-1d1957a9cf0bda2c16b453d58567a2c5L3445

**Comment by chris-fuller** [comment]
@sdillingham : Looks like that was done Jul 13, 2015 before my time.
https://github.com/SCPR/KPCC-iPhone/commit/5f3bf5878c1360bf6d14d4a3672122323614b050

There was some code left in that was not utilized, so I stripped that out in the commit you referenced.

**Comment by chris-fuller** [comment]
@vsinghkpcc: #163 has been merged to `develop` and a build is now available via TestFlight. Please feel free to close this issue.

**Comment by chris-fuller** [comment]
FYI: I was incorrect when I mentioned "this branch has the old SSO work removed". It was actually done on #171.
