### ISSUE TITLE
TritonAd.m line 24

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#126]
#### in -[TritonAd initWithDict:]

* Number of crashes: 30
* Impacted devices: 30

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/5681e2cef5d3a7f76bb65e7f](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/5681e2cef5d3a7f76bb65e7f)

**Comment by chris-fuller** [comment]
Related issue: https://github.com/SCPR/KPCC-iPhone/issues/121
