### ISSUE TITLE
Testflight build for 3.4.3

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#136]
AC
- [ ] There is a build distributed on Testflight for 3.4.3 

Note: #97 and #112 might be addressable, but not required for 3.4.3

**Comment by chris-fuller** [comment]
Version 3.4.3 (862) has been uploaded.

**Comment by chris-fuller** [comment]
Version 3.4.3 (876) has been uploaded.

**Comment by chris-fuller** [comment]
Version 3.4.3 (882) has been uploaded.

**Comment by chris-fuller** [comment]
Version 3.4.3 (914) has been uploaded.

**Comment by chris-fuller** [comment]
Version 3.4.3 (925) has been uploaded.
