### ISSUE TITLE
Catalog iPhone App Dependencies

### ISSUE THREAD

**Issue by chris-fuller** [SCPR/KPCC-iPhone#144]
For each dependency, determine the following attributes:

* Latest Version
* Installed Version
* Installation Method (Source, Pod, Framework, etc.)
* Is dependency generating warnings (both compile time and static analyzer)?
* Notes, such as whether or not the dependency is needed/utilized, or any other relevant info.

AC

* Documentation on dependencies (including all attributes, except notes which are optional)

**Comment by chris-fuller** [comment]
https://docs.google.com/spreadsheets/d/14c6NvAjL5b77XRjQsatqIWFNi-RoIWzvGlLESgA2kec

**Comment by sdillingham** [comment]
All the Auth0 Lock dependencies aren't technically necessary unless/until we implement Auth0 in the app. It's your call @chris-fuller whether you want to prune them for now.
