### ISSUE TITLE
QA 3.4.3 (974)

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#173]
AC: Build 974 has been QAed and is ready for submission to Apple.

**Comment by chris-fuller** [comment]
Version 3.4.3 (974) has been submitted to Apple for review. However it has NOT completed final QA yet.

**Comment by chris-fuller** [comment]
Version 3.4.3 (974) has been submitted to Apple for review.

NOTE: Two issues were discovered during QA, but they are not regressions and exist in the current App Store release.
