### ISSUE TITLE
SSO AUth0 UI Investigation

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#193]
AC
- [x] Install Auth0 SDK
- [x] User can signup & sign-in
- [x] Possible customization is reviewed between dev and design

**Comment by chris-fuller** [comment]
New test project created, ready for customization.

Customization options are (vaguely) documented here:

https://auth0.com/docs/libraries/lock-ios/customization

**Comment by chris-fuller** [comment]
Ready to review with @tinykb in-person.
