### ISSUE TITLE
Auto0 Dashboard Configuration

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#194]
AC: List configurable options.

**Comment by chris-fuller** [comment]
Configurations to be discussed:

* Email provider
* Email templates
* Login Page
* Password Reset Page
* Social Login (Google and Facebook)
* Possibly delete all users, delete database connection, and start fresh
* Password Strength
* Account Settings: Friendly Name, Logo URL, Support Email and Support URL
* Error Pages

**Comment by vsinghkpcc** [comment]
We'll close this ticket, but use this list to create other tickets we can break up for different members of the team.
