### ISSUE TITLE
UIKit

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#200]
#### in -[UIView(Internal) _addSubview:positioned:relativeTo:]

* Number of crashes: 48
* Impacted devices: 18

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55e44ffcf5d3a7f76baf3407](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55e44ffcf5d3a7f76baf3407)

**Comment by chris-fuller** [comment]
Moving to `Review` since iOS 8 is no longer supported.

**Comment by chris-fuller** [comment]
Not seen seen v3.3.5. Moving to `Review`. Can be closed.
