### ISSUE TITLE
Configure GA for iPhone App

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#204]
AC
- [ ] There is a a google account we can use to configure with our iPhone app for GA

**Comment by vsinghkpcc** [comment]
https://developers.google.com/analytics/devguides/collection/ios/v3/

Note that when you click to "get a config file" you're prompted to create a google developers app associated with a google account.

**Comment by vsinghkpcc** [comment]
Account created, access shared with Sean and Chris, and config file delivered to Chris for implementation.

**Comment by chris-fuller** [comment]
Committed here: https://github.com/SCPR/KPCC-Config/commit/17163266349fce9ecd4c6e3169ec6272876605ac
