### ISSUE TITLE
SSO: research token expiration in Auth0

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#208]
AC:  we understand how we can confidently keep a user signed in to the app indefinitely (until/unless they sign out)

**Comment by chris-fuller** [comment]
I've found this information on the Auth0 site:

![screen shot 2016-06-24 at 7 40 34 pm](https://cloud.githubusercontent.com/assets/16296673/16354323/959f5faa-3a44-11e6-8428-3e4be5357db9.png)

I have just opened a support request with Auth0 to confirm that refresh tokens never expire (unless manually revoked of course).

I'll update this ticket once we get a response.

**Comment by chris-fuller** [comment]
From Auth0:

Q: Do refresh tokens expire?

A: No, because a refresh token is a special kind of token that can be used to obtain a renewed id_token (JWT) at any time. Refresh tokens must be stored securely by an application because they essentially allow a user to remain authenticated forever.

**Comment by chris-fuller** [comment]
We are storing the refresh token in the iOS keychain. So closing this issue.
