### ISSUE TITLE
SSO: Analytics MVP

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#217]
AC
- For fabric we track:
- [x] Log In
- [x] Sign Up

- For GA we track:
- [x] Log In
- [x] Sign Up
- [ ] ~~Ticket Tuesday Impression~~
- [x] Ticket Tuesday Click

**Comment by vsinghkpcc** [comment]
Suggestions for GA Naming:

Category for all events: "SSO"

Action: "LoggedIn" 
Action: "SignedUp" 
- Label from TT Ad: "ticketTuesdayAd"
- Label from Profile: "ProfileScreen"

Action: "ticketTuesdayAdLoaded" 
Action: "ticketTuesdayAdClicked" 
- Label: [the best identifier we can pass for that giveaway, maybe the date? or the eloqua ID?]

**Comment by chris-fuller** [comment]
@vsinghkpcc: It will take a bit more work to get the `ticketTuesdayAdLoaded ` event. Are we ok with just the `ticketTuesdayAdClicked` event for now? (and therefore rely on AdTech for the impressions).

Also, I've named it `ticketTuesdayAdTapped` instead. Just FYI.

**Comment by chris-fuller** [comment]
And note, that I've set it up to pass through all parameters that are presented on the clickthrough URL to the label. Let me know if that will work for now.

**Comment by sdillingham** [comment]
Maybe this isn't MVP, but wouldn't it make sense to set a custom dimension for logged in users?

https://developers.google.com/analytics/devguides/collection/ios/v3/customdimsmets#considerations

Setting and sending a userID would be useful as well:

https://developers.google.com/analytics/devguides/collection/ios/v3/user-id#before-begin

**Comment by vsinghkpcc** [comment]
@chris-fuller just tracking ad taps for now is fine, and naming is good to go.
@sdillingham those are great, thanks for pointing it out, but yeah, not MVP - I'll make a different ticket to add that to the next release.
