### ISSUE TITLE
HLS Discontinuities Seem to Confuse Live State

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#22]
A couple of less-than-stellar restarts this morning left a pair of discontinuities in the HLS stream playlist. Something about that seems to have very much confused the player UI. I loaded the app, clicked play, and got "Live Behind Live":

![img_0886](https://cloud.githubusercontent.com/assets/204350/6003007/1c3be6f6-aac6-11e4-8c06-ff6197e6420f.PNG)

Clicking pause also only gave me the option of going live, where I believed I already should be:

![img_0887](https://cloud.githubusercontent.com/assets/204350/6003016/36529a44-aac6-11e4-94ca-3033c4a86120.PNG)

We'll have to think about the cleanest way to recreate these conditions on a test server.

**Comment by ewr** [comment]
From poking around with a test player, it seems like something about the discontinuity is causing AVPlayer to think the date on the live segments is later than it actually is. I suspect `currentDate` is giving a time slightly in the future, leading to the UI issues seen above.

The server's perspective on time looks correct, but for some reason there appear to be less HLS segments in our 256k stream, so I suspect something that happens what that starts playing causes the time display issue. It should wash itself out of the production stream over the next few hours.

On the player side, though, we should just handle any date in the future as "Live".

**Comment by bhawk9780** [comment]
While I can't get my build (3.0.0 build 10) to trick out into this Live Behind Live state, I am noticing today that after a rewind, when I seek back to live it never is able to return any closer than 2 minutes behind live. I think this is the same problem but I don't have the "Live Behind Live" text but instead am marooned in a continual "2 minutes behind live" state and cannot actually get back to live without switching to OnDemand and then back to the Live stream.

  I'll investigate further to see why this is happening. From my initial findings, A "Back to Live" seek uses the last registered "max seekable date" (based off of AVPlayer's seekable time ranges) and even though the requested date is usually around 45 to 50 seconds behind "now", the end result seeks us slightly over 2 minutes behind live.

**Comment by bhawk9780** [comment]
going to leave this open and close with a commit at some point that will ensure even if everything blows up one day the user will never be looking at text that reads "Live behind Live"

**Comment by bhawk9780** [comment]
meh. closing by hand.
