### ISSUE TITLE
SSO: Ticket Tuesday MVP Submitted to Apple

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#223]
AC
- [x] Build has been QAed on test devices
- [x] Submitted to Apple for review

**Comment by chris-fuller** [comment]
@vsinghkpcc: The AC for submission to Apple is blocked pending acceptance of the agreement. My suggestion is that we ~~strikethrough~~ that one AC, and focus on QA for now. Sound good?
