### ISSUE TITLE
Apple Bitcode Warning

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#226]
AC: Fix the issue causing the email warning from Apple

**Comment by chris-fuller** [comment]
Let's assume it's an iTunes bug for now (see attached SO threads).

http://stackoverflow.com/questions/38061045/unexpected-machine-code-warning-from-itunes-connect
http://stackoverflow.com/questions/38069145/unexpected-machine-code-will-this-affect-app-approval

We can reevaluate if we continue to receive the email warnings and/or we have submission issues.
