### ISSUE TITLE
SSO: Fix Authenticating with Facebook App

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#227]
NOTE: waiting for response from Auth0.

AC: If a user who has the FB app on their phone, logs into our app via FB, authentication processes through the FB app.

**Comment by chris-fuller** [comment]
Looks like this is expected behavior for iOS 9:

https://developers.facebook.com/blog/post/2015/10/29/Facebook-Login-iOS9/
