### ISSUE TITLE
SSO: Cookie Targeting Ad Url

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#228]
AC
- [ ] ~~Cookies are utilized when requesting ads from the ad server~~
- [x] Cookies can be utilized when requesting ads from the ad server

**Comment by chris-fuller** [comment]
`http://adserver.adtechus.com/bind?ckey1=[key];cvalue1=[value];expiresDays=[expiration];misc=[timestamp]`

**Comment by chris-fuller** [comment]
@vsinghkpcc: The code to support this has been implemented, but is not enabled. It will take one simple code change to enable it once we're ready,

**Comment by vsinghkpcc** [comment]
@chris-fuller I ran a test campaign on production with the cookie targeting set, and it delivered zero impressions, which is the expected behavior, so this is a viable solution.
