### ISSUE TITLE
SSO: No auto login after re-install

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#235]
AC: Regardless of a user's past actions, if they have deleted and then re-installed the app they should not be auto-logged in.

**Comment by chris-fuller** [comment]
@vsinghkpcc: Emailed Auth0 to get their input before implementing a solution.

**Comment by chris-fuller** [comment]
PR: https://github.com/SCPR/KPCC-iPhone/pull/239
