### ISSUE TITLE
SSO: iPhone 4s - UI issues when authenticating via email

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#236]
AC: An iPhone 4s user can see the email address and password fields as they enter their information.

(Right now the email field is not visible)

**Comment by jgeorges** [comment]
Another issue, unable to exit Your Profile Welcome screen if log in process canceled.

**Comment by jgeorges** [comment]
![img_0003](https://cloud.githubusercontent.com/assets/915664/17194537/58a4d688-540d-11e6-807e-75a001247bff.PNG)
![img_0002](https://cloud.githubusercontent.com/assets/915664/17194544/5c62f5d4-540d-11e6-8084-cdda21eea607.PNG)

**Comment by chris-fuller** [comment]
@vsinghkpcc @jgeorges: This ticket is blocked until we have an iPhone 4S that we can use for development builds. Please let me know if and when there is an iPhone 4S that I can use for a few days. Thanks!

**Comment by chris-fuller** [comment]
BTW, we already implemented a fix for this issue, so it is curious that is occurring. The first step will be to look into why our iPhone 4S UI customizations are not being applied.
