### ISSUE TITLE
v3.4.5 iOS testing and release

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#247]
AC
- [x] v.3.4.5 has been QAed and approved for release
- [x] it has been submitted to the Apple Store

**Comment by chris-fuller** [comment]
@vijay: I've QA'ed 3.4.5 using test plan. I think you said you also tested this build, correct?

**Comment by chris-fuller** [comment]
@vsinghkpcc: I've QA'ed 3.4.5 using test plan. I think you said you also tested this build, correct?

**Comment by vsinghkpcc** [comment]
@chris-fuller Yep, and everything went as expected, so unless you suggest otherwise, I'd mark it as OK to release.
