### ISSUE TITLE
Audio Player Prototype: Swift 3 migration

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#251]
TIMBOXED

AC 
- [x] Use automated migration tool
- [x] Perform manual migration tasks

**Comment by chris-fuller** [comment]
Leaving changes in branch:

https://github.com/SCPR/KPCC-iOS/tree/swift-3-migration

This is a rough quick conversion to Swift 3 and should not be used.
It exists as an example and to show that it can be done easily.
Instead, plan and redo the Swift 3 conversion from master branch.
