### ISSUE TITLE
On Demand Content for the Prototype App

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#272]
AC

- [x] The programs are listed 
- [x] The episodes are listed for each program
- [x] The episodes are playable

**Comment by jeffc-kpcc** [comment]
Within our iOS Testbed app, I've got the Program API stuff done and the Episode API stuff partially done, with enough in place to browse both. I also created a browsing interface to select Programs and Episodes within them.

This doesn't actually allow you to switch what you're playing yet, though. I'll get on that next week.

**Comment by jeffc-kpcc** [comment]
This is working. You can:

* I've got episodes playing, sequentially, with each segment playing in succession.

* This was significantly more work to do than I expected, and I would say that this '2' turned into a '3'.

* But it's working!

**Comment by vsinghkpcc** [comment]
I've updated the estimate to better reflect the effort it took to complete.
