### ISSUE TITLE
Improving Troubleshooting Logging Audit

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#273]
AC

- [x] Determine exact data (client side and server side) that we need to properly troubleshoot a streaming issue
- [x] Determine a reasonable data retention policy
- [x] Establish a submissions process that ties to server side data

**Comment by jeffc-kpcc** [comment]
I created a logging class for our iOS Testbed project that logs the following:

* Short text summary describing the log entry (ie. "Pressed pause")
* A timestamp with sub-millisecond precision (may be unnecessary)
* Within each log entry: Play status, reachability
* Arbitrary dictionary content

The class includes methods to return the above data either in a purely human-readable form (text or HTML, summaries only) OR json.

I also created a simple viewer to look at summaries, including a button that allows testers to email json data to us. This will work for the time being until we have some sort of feedback form that the json info can be sent by.

As for retention policy on the client-side, I designed the logger to hold no more than 500 log entries and those going back no further than 6 hours. We can tweak this as needed.

All that I really have left is to add logging to more in-app events, as needed, to help us debug issues and make sure that it can be reasonably compared to server-side data. I will get on that next week.

**Comment by jeffc-kpcc** [comment]
Made the log time interval into an Int, rather than a TimeInterval (Double). We probably don't need to extra precision, and this makes log data look a little nicer.

If we need it back, it's a trivial change.

**Comment by jeffc-kpcc** [comment]
Added some more data to be logged when playing on-demand audio.

I think this ticket is effectively done, though I'm sure we'll want to adjust what logging data we collect over time to help debug certain scenarios as they come up (this class is pretty flexible, and can be used for just about any data collection we want).
