### ISSUE TITLE
Fix Missing Program Tiles

### ISSUE THREAD

**Issue by nakedsushi** [SCPR/KPCC-iPhone#275]
@nakedsushi commented on [Tue Feb 07 2017](https://github.com/SCPR/SCPRv4/issues/758)

(build 1309)

Can you investigate why the following programs don't have program tiles? I see one in the program tile directory that Katie uploaded, so either it didn't make it to the server (my bad!) or there's a file name mismatch somewhere?  I've attached the correct tiles to this ticket.

AC:
- [ ] Invisibilia has program tiles
- [ ] Q has program tiles
- [ ] The Awards Show has program tiles
- [ ] The Brood has program tiles
- [ ] The Mash Up has program tiles
- [ ] The Ride

![program_tile_invisibilia](https://cloud.githubusercontent.com/assets/360040/22703857/775302f2-ed1a-11e6-9eb7-0e1fba3feb7f.jpg)
![program_tile_invisibilia 2x](https://cloud.githubusercontent.com/assets/360040/22703856/774c82a6-ed1a-11e6-9443-31a08ee7d3ff.jpg)

![program_tile_q-with-jian-ghomeshi](https://cloud.githubusercontent.com/assets/360040/22705061/e28c6f5a-ed1e-11e6-85f7-63ef353b5be9.jpg)
![program_tile_q-with-jian-ghomeshi 2x](https://cloud.githubusercontent.com/assets/360040/22705060/e2855b02-ed1e-11e6-9642-738aee3c53c5.jpg)

![program_tile_awards-show-show](https://cloud.githubusercontent.com/assets/360040/22705096/07127018-ed1f-11e6-95db-71db96610ed2.jpg)
![program_tile_awards-show-show 2x](https://cloud.githubusercontent.com/assets/360040/22705095/07124836-ed1f-11e6-8c03-17d719c99c31.jpg)

![program_tile_brood](https://cloud.githubusercontent.com/assets/360040/22705111/1f132478-ed1f-11e6-9b15-040e63ca04fc.jpg)
![program_tile_brood 2x](https://cloud.githubusercontent.com/assets/360040/22705112/1f14d7fa-ed1f-11e6-8059-d8b60f02ef2f.jpg)

![program_tile_mash-up-americans](https://cloud.githubusercontent.com/assets/360040/22705130/31f75834-ed1f-11e6-950d-33288fc9368e.jpg)
![program_tile_mash-up-americans 2x](https://cloud.githubusercontent.com/assets/360040/22705131/31fc259e-ed1f-11e6-9382-3ccc63c900e8.jpg)

![program_tile_ride](https://cloud.githubusercontent.com/assets/360040/22705180/676f064c-ed1f-11e6-90cb-dad4426b4d9c.jpg)
![program_tile_ride 2x](https://cloud.githubusercontent.com/assets/360040/22705179/676e1cb4-ed1f-11e6-97f9-7a7b1b5d61a7.jpg)

**Comment by jeffc-kpcc** [comment]
These have all been resolved. They were all uploaded, but the filenames did not match the slugs. I've renamed the files as described below:

```
program_tile_invisibilia@2x.jpg			-> program_tile_Invisibilia@2x.jpg
program_tile_invisibilia.jpg			-> program_tile_Invisibilia.jpg
```

```
program_tile_awards-show-show@2x.jpg		-> program_tile_the-awards-show-show@2x.jpg
program_tile_awards-show-show.jpg		-> program_tile_the-awards-show-show.jpg
```

```
program_tile_brood@2x.jpg			-> program_tile_the-brood@2x.jpg
program_tile_brood.jpg				-> program_tile_the-brood.jpg
```

```
program_tile_mash-up-americans@2x.jpg		-> program_tile_the-mash-up-americans@2x.jpg
program_tile_mash-up-americans.jpg		-> program_tile_the-mash-up-americans.jpg
```

```
program_tile_ride@2x.jpg			-> program_tile_the-ride@2x.jpg
program_tile_ride.jpg				-> program_tile_the-ride.jpg
```

```
program_tile_q-with-jian-ghomeshi@2x.jpg	-> program_tile_q@2x.jpg
program_tile_q-with-jian-ghomeshi.jpg		-> program_tile_q.jpg
```
