### ISSUE TITLE
Make SSO work with Pre-roll in Testbed

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#279]
AC

- [x] A logged in user can tap the visual that accompanies a pre-roll and their information is successfully passed to an eloqua form
- [x] When tapping the pre-roll, a user not logged in user is prompted to sign up via the default Auth0 functionality, and their information is successfully submitted after completing sign up

**Comment by jeffc-kpcc** [comment]
Done!
