### ISSUE TITLE
Sleep Timer UI Bug

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#284]
STR
1) Play the Live Stream
2) Set a sleep timer for 5 mins
3) See the menu does not dismiss

OR

1) Set a sleep timer for 5 mins
2) see the UI goes wonky

AC
- [x] A user can set the sleep timer, and the Pre-roll / Live Stream and it's associated UI engages correctly

**Comment by jeffc-kpcc** [comment]
Resolved. Will be testable in tomorrow's build.
