### ISSUE TITLE
KPCC Plus in TestFlight App

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#288]
AC

- [x] KPCC Plus works in the Test Flight version of the app

**Comment by jeffc-kpcc** [comment]
Verified that this works during off-peak hours. Got the drop-down, which - when tapped - allows users to select a stream (the actual KPCC Plus stream isn't up, however, so I was unable to actually _listen_ to it).

Note that this is dependent on changing the kpccPlusDriveStart and kpccPlusDriveEnd values in Parse, however, and not in our CMS.
