### ISSUE TITLE
App hits SCPRv4 schedule endpoints more often than is necessary

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#37]
Looking through SCPRv4's New Relic info this morning, I noticed that the app is doing a schedule update every three minutes. That leads to load on the schedule endpoint of approximately 230rpm during peak morning hours:

![screen shot 2015-05-07 at 10 28 30 am](https://cloud.githubusercontent.com/assets/204350/7517611/107c41c6-f4a4-11e4-9229-c3bc6f4c8dff.png)

Is there a reason that we're hitting the API endpoint every time instead of caching the schedule response and checking whether our current time is still within the start and end times it gave us? 

The API function is reasonably light, but can't be cached well since these requests are all using timestamps. As listenership increases, the current setup would pose an increasing load on the web frontends.

**Comment by benkpcc** [comment]
This is a refactor I've been wanting to add in for a while, and now is a good time to do it now that the app is querying the full schedule for the new display feature, which I can cache. We can add this in as part of 3.3.
