### ISSUE TITLE
SSO UI flow in iPhone

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#60]
AC
1) There is a profile menu option
2) When a user is not signed in, the profile option cues the SSO flow
3) The SSO flow allows the user to sign up or log in
4) When a user is signed in, the profile menu option is dumb simple

**Comment by benkpcc** [comment]
@vsinghkpcc and @sdillingham : Is part of AC 3 here to have the entire flow w/ complete design treatment?

**Comment by sdillingham** [comment]
Good question - no, I don't think so just yet. Getting a functional implementation is a good first step for now, and I expect I won't have design cycles to devote to this until the next sprint.
