### ISSUE TITLE
Submit KPCC Plus Stream for Review

### ISSUE THREAD

**Issue by vsinghkpcc** [SCPR/KPCC-iPhone#68]
AC

1) We have a way to change the KPCC Plus URL without issuing a new update
2) The capabilities for KPCC Plus Stream is submitted for Review

**Comment by benkpcc** [comment]
So as mentioned as a possibility in planning, I'm heavily in favor of the Parse option. It's a simple change client-side and just needs a little bit of testing on my part.

Logic is when the pledge-drive is not happening, the URL setting in Parse is set to an identical value as the regular stream. When Apple is to review our app, we spoof the API to set the pledge_drive boolean to true. When the pledge drive begins in October, we change the setting in Parse to http://kpccplus.scprdev.org/sg/kpcc-plus.m3u8 (if that's still the URL for plus by then) and everything should just work.
