### ISSUE TITLE
Add "Album Art" to Lock Screen

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#75]
It seems like a good idea to add "album art" to the lock screen when a user is listening to audio from the app. This would be a square image that we either have in the app, or load into the app from an external resource.

Easiest approach would just be to use a generic KPCC image all the time, and I think this would be an improvement over the current lack of an image.

It would be great to have per-program images to show based on what's currently playing, but I'm not sure it we have available art that would make sense here.

Ping: @sdillingham

**Comment by sdillingham** [comment]
@ewr - sorry about the empty pixels at the edges of the first file I sent you - here's an updated version to drop into the next release:

![coverart-kpcc](https://cloud.githubusercontent.com/assets/442483/10022898/05acf5f2-6104-11e5-9100-41ede8da60d3.png)

**Comment by ewr** [comment]
This is released in 3.4.1.
