### ISSUE TITLE
Change Session Timeout for Returning Listeners

### ISSUE THREAD

**Issue by ewr** [SCPR/KPCC-iPhone#76]
Currently, if a user returns to the app within ~4 hours (really if their start position is still in the buffer), they are defaulted to the position where they left off and treated as a continued session. 

Continued sessions don't currently get prerolls, so this lowers our available impressions in the midday and afternoon. It also may result in user confusion if they don't realize they're being returned to a non-live point.

I'd like to alter that logic to say that a session is continued if a) the position is still available and b) the session was last active within the last hour.

Eventually, it would make sense to offer users some UI choices around resuming where they left off or returning to live, but I suspect this smaller change would get us closer to doing what the user expects. It would also open up some number of additional impressions, though it's hard to say exactly what that number might be.

Ping: @vsinghkpcc @sdillingham

**Comment by vsinghkpcc** [comment]
@ewr I like your solution!

**Comment by sdillingham** [comment]
I like this, but I could make a case for the "session last active" window being within the last two hours instead of one hour. I don't have strong feelings about this, so if @ewr and @vsinghkpcc both 1 hour as the window for what constitutes a resumed session.

**Comment by ewr** [comment]
Eventually we could even implement this as a setting for power users, but I tend to think an hour right now.

**Comment by ewr** [comment]
Tagged the wrong issue in the commit message, but the initial implementation for this is in 921ef8167fe318a3ae6b63e0f1921cdbe0e78080. 

When a) returning to foreground or b) starting to play via a remote control event, check to see if the session has been idle for an hour or more. If so, reset the session, causing playback to start from live and the user to be eligible for preroll.

b76b042d3d084749d785cdb2d663d5742914e66d also allows preroll on the live stream after the user has started their app session by listening to on-demand content.

**Comment by ewr** [comment]
This will be in build 831, which should hit testflight beta in the next hour or two.
