### ISSUE TITLE
All Programs view needs table section headers for KPCC Programs and Other Programs

### ISSUE THREAD

**Issue by sdillingham** [SCPR/KPCC-iPhone#79]
With #74 now implemented, we need to add clarity to the UI to indicate the two blocks of alpha sorted lists (KPCC Programs, Other Programs) that now populate that table view. Standard tableview section headers for each block should do the trick.

**Comment by ewr** [comment]
<img width="389" alt="screen shot 2015-09-11 at 9 11 29 pm" src="https://cloud.githubusercontent.com/assets/204350/9829231/fb8d3d08-58c9-11e5-87ff-6c703bf0628d.png">
<img width="384" alt="screen shot 2015-09-11 at 9 13 23 pm" src="https://cloud.githubusercontent.com/assets/204350/9829232/fe5dd272-58c9-11e5-8c4e-d3204c697b5a.png">
