### ISSUE TITLE
ScheduleOccurrence.swift line 37

### ISSUE THREAD

**Issue by scpr-iphone-fabric** [SCPR/KPCC-iPhone#97]
#### in specialized ScheduleOccurrence.init(dict : NSDictionary) -> ScheduleOccurrence

* Number of crashes: 9
* Impacted devices: 9

There's a lot more information about this crash on crashlytics.com:
[https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fa23e2f5d3a7f76b147055](https://fabric.io/scpr/ios/apps/org.americanpublicmedia.kpccradio/issues/55fa23e2f5d3a7f76b147055)

**Comment by ewr** [comment]
Not sure what input data is causing this... I took a shot at making our handling a little more forgiving in 7937538ca606d00ed72e8945eea3ba7e4bc96ca9, but I don't know what data would be tripping that.

**Comment by ewr** [comment]
Closing for now, but we'll reopen if this crash appears in 3.4.1.

**Comment by sdillingham** [comment]
This is resulting in enough crashes in 3.4.2 that I'm reopening.
